# Generated by Django 3.1.4 on 2020-12-30 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='session_token',
            field=models.CharField(default='t', max_length=10),
        ),
    ]
